# Generated by Django 4.2.2 on 2024-02-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=18)),
                ('nombre', models.TextField()),
                ('apellidoPaterno', models.TextField()),
                ('apellidoMaterno', models.TextField()),
                ('correo', models.EmailField(max_length=254)),
                ('telefonoCasa', models.CharField(max_length=10)),
                ('telefonoCelular', models.CharField(max_length=10)),
                ('carrera', models.CharField(max_length=30)),
                ('procedencia', models.CharField(max_length=30)),
            ],
        ),
    ]
